export interface ApiErrorPayload {
  // RFC 7807 (kinetic-rpc)
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;
  code?: string;
  retryable?: boolean;
  details?: any;
  request_id?: string;

  // Fallback from desktop api_commands.rs
  message?: string;
}

export class KineticError extends Error {
  public code?: string;
  public title: string;
  public status?: number;
  public retryable?: boolean;

  constructor(message: string, code?: string, title?: string, status?: number, retryable?: boolean) {
    super(message);
    this.name = 'KineticError';
    this.code = code;
    this.title = title || 'Error';
    this.status = status;
    this.retryable = retryable;
  }
}

export function interceptApiError(rawError: any): KineticError {
  // 1. Try to parse if it's a string (since Tauri invoke rejects with strings)
  let parsed: ApiErrorPayload | null = null;
  if (typeof rawError === 'string' && rawError.startsWith('{')) {
    try {
      parsed = JSON.parse(rawError);
    } catch {
      // ignore parsing failure
    }
  } else if (typeof rawError === 'object' && rawError !== null) {
    parsed = rawError;
  }

  // 2. If we successfully parsed a structured error payload
  if (parsed) {
    // Handle RFC 7807 from kinetic-rpc (daemon is online, but command failed)
    if (parsed.detail) {
      return new KineticError(
        parsed.detail,       // Use the beautiful English detail as the main message
        parsed.code,
        parsed.title,
        parsed.status,
        parsed.retryable
      );
    }

    // Handle Hard Network/OS Failures generated by our Tauri Rust wrapper
    if (parsed.code === 'ERR_NETWORK') {
      return new KineticError(
        "The Kinetic Daemon is currently offline or unreachable. Please go to Settings to restart the daemon.",
        "ERR_NETWORK",
        "Daemon Offline"
      );
    }
    if (parsed.code === 'ERR_PARSE') {
      return new KineticError(
        "Failed to parse the response from the daemon. The internal data might be corrupted.",
        "ERR_PARSE",
        "Data Parsing Error"
      );
    }
    if (parsed.code === 'ERR_IO') {
      return new KineticError(
        "A local file system error occurred on the daemon. Could not read or write required files.",
        "ERR_IO",
        "File System Error"
      );
    }

    // Fallback for unknown JSON structures
    return new KineticError(parsed.message || JSON.stringify(parsed), parsed.code);
  }

  // 3. Fallback for raw unparsed strings (e.g. OS panics that leak out)
  const rawStr = String(rawError);
  if (rawStr.includes("ConnectionRefused") || rawStr.includes("os error 111") || rawStr.includes("tcp connect error")) {
     return new KineticError(
        "The Kinetic Daemon is currently offline or unreachable. Please go to Settings to restart the daemon.",
        "ERR_NETWORK",
        "Daemon Offline"
      );
  }

  return new KineticError(rawStr, "UNKNOWN_ERROR");
}
